In [3]:
import tensorflow as tf
import numpy as np

In [10]:
def model():
    inpt = tf.keras.Input(shape=(None,24,2))
    compression_layer = tf.keras.layers.LSTM(16)
    x = tf.keras.layers.TimeDistributed(compression_layer)(inpt)
    x = tf.keras.layers.LSTM(32, return_sequences=False)(x)
    y = tf.keras.layers.Dense(1)(x)
    return tf.keras.Model(inputs=[inpt], outputs=[y])

In [11]:
md = model()

In [12]:
md.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, None, 24, 2)]     0         
                                                                 
 time_distributed (TimeDistr  (None, None, 16)         1216      
 ibuted)                                                         
                                                                 
 lstm_1 (LSTM)               (None, 32)                6272      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 7,521
Trainable params: 7,521
Non-trainable params: 0
_________________________________________________________________


In [ ]:
(batch, tidsekvens, timmar-24, features)

In [ ]:
#För flera patienter

# pat 1, 400 dagar information, 3 features
# pat 2, 200 dagar, 3 features
# pat 3, 650 dagar

#400+200+650...

In [4]:
dataset = np.random.randn(1000,3)

In [5]:
X = dataset[:,0:2]
y = dataset[:,2].reshape(-1,1)

In [63]:
X

array([[ 1.23374711,  0.87039289],
       [ 0.34624638,  2.57564436],
       [-1.16498725, -0.33417746],
       ...,
       [ 0.0047085 ,  0.9532612 ],
       [-0.65083627,  0.78013396],
       [ 1.43733262, -0.30399414]])

In [8]:
y.shape
y

array([[ 5.79642660e-02],
       [ 1.08811435e+00],
       [ 1.95044481e+00],
       [ 3.59603075e-01],
       [ 1.42397296e+00],
       [-6.15981007e-01],
       [-2.45127609e-01],
       [-1.89135700e-01],
       [ 8.11750218e-01],
       [-3.14798581e-01],
       [ 9.37682494e-01],
       [ 2.26054178e+00],
       [ 4.67871430e-01],
       [ 5.91486756e-01],
       [-6.42785954e-01],
       [ 9.27847087e-01],
       [ 3.89248287e-01],
       [ 4.07981595e-01],
       [ 3.52124754e-01],
       [ 7.43651143e-02],
       [ 1.01032468e-02],
       [-7.51697213e-01],
       [-8.03789531e-01],
       [-6.46258702e-01],
       [ 2.97152411e-02],
       [-3.01331858e-01],
       [ 5.34080386e-02],
       [ 1.29258534e+00],
       [-5.46001582e-01],
       [ 2.53959420e-01],
       [ 1.13250439e+00],
       [-1.08258359e+00],
       [ 5.38228835e-01],
       [-1.14567407e+00],
       [-1.60946303e+00],
       [-5.00489676e-01],
       [ 1.59142828e-01],
       [-3.14212782e-01],
       [-5.8

In [ ]:
data_index = t0, t1, t2, t3, t4, t5, t6, t7, t8, t9

X      = data[0:2], data[1:3], data[2:4], data[3:5]
y      = data[2],   data[3],   data[4],   data[5]

In [27]:
np.random.randn(1,30,2)

array([[[ 0.3547007 ,  0.62427427],
        [ 0.69103136,  0.41928665],
        [-0.28613059, -0.70808274],
        [ 1.97177952, -0.02038301],
        [ 1.13053887, -0.17912626],
        [-0.40873936, -0.36435522],
        [ 0.27591632,  0.03234693],
        [-0.19099702,  0.90567913],
        [-1.26947119,  0.06821572],
        [-0.23658166, -2.0187707 ],
        [ 0.42250275,  0.44438823],
        [-0.7062238 ,  0.5178107 ],
        [-0.13980854, -0.07367048],
        [ 0.71754874,  0.35600421],
        [ 0.06308128,  1.66665731],
        [ 1.06936755, -2.13930001],
        [-0.93666464,  1.05791304],
        [-0.13240307,  1.3522191 ],
        [ 0.28894281, -1.08220162],
        [ 1.79913757,  0.10235682],
        [ 0.30346258,  1.50621451],
        [-0.76321964, -0.02756912],
        [ 0.01325052, -1.09533205],
        [ 0.81890223,  0.26608928],
        [-0.66197012, -0.05732439],
        [ 1.07476113,  0.71432641],
        [-0.1040984 ,  2.28046856],
        [-1.17136933,  0.837

In [30]:
md.predict(np.random.randn(10,30,2))

array([[0.00475262],
       [0.03330417],
       [0.07839676],
       [0.01074573],
       [0.01772285],
       [0.04732184],
       [0.02092865],
       [0.05183602],
       [0.0240394 ],
       [0.04857615]], dtype=float32)

In [31]:
X = np.random.randn(128,30,2)

In [32]:
y = np.random.randn(128,1)

In [35]:
md.compile("adam", loss="mse")

In [37]:
md.fit(X,y,batch_size=4)

32/32 [==============================] - 1s 6ms/step - loss: 0.9151
